spring:
 application:
  name: orchestrator-service
 rabbitmq:
  host: 192.168.144.128
  username: guest
  password: guest
  directExchange: listing
  updateQueue: update
  deleteQueue: delete
 main:
  allow-bean-definition-overriding: true
eureka:
 client:
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
  preferIpAddress: true
server:
 port: 8080


