couchbase:
  bucket: listing
  hostname: localhost
  password: password
  username: Administrator
server:
  port: 8082
spring:
  application:
    name: listing-service
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    deleteQueue: delete
    directExchange: listing
    host: 192.168.144.128
    password: guest
    updateQueue: update
    username: guest
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}
  instance:
    preferIpAddress: true
