couchbase:
  bucket: listing
  hostname: localhost
  password: password
  username: Administrator
server:
  port: 8003
spring:
  application:
    name: listing-service
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    deleteQueue: delete
    directExchange: listing
    host: 192.168.144.128
    password: guest
    updateQueue: update
    username: guest
eureka:
  client:
    prefer-same-zone-eureka: true
      region: region1
      service-url:
        zone1: http://localhost:8761/eureka/
        zone2: http://localhost:8762/eureka/
      availability-zones:
        region1: zone1,zone2
