server:
  port: 9002
spring:
  application:
    name: customer-service
  profiles:
    active: zone2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/customer
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    preferSameZoneEureka: true
    region: region1
    serviceUrl:
      - zone1: http://localhost:8761/eureka/
      - zone2: http://localhost:8762/eureka/
    availabilityZones:
      region1: zone1,zone2
