server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/customer
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: customer-service
    preferIpAddress: false
