server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: region1
    serviceUrl:
      - zone1: http://localhost:8761/eureka/
      - zone2: http://localhost:8762/eureka/
    availabilityZones:
      region1: zone1,zone2

spring:
  profiles:
    active: zone2
